---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# primer

<!-- badges: start -->
<!-- badges: end -->

The goal of primer is to .maintain functions used in [Primer of Ecology Using R] (https://hankstevens.github.io/Primer-of-Ecology/)

## Installation

You can install the released version of primer from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("primer")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("HankStevens/primer")
```
## Example

Stochastic density-independent population dynamics.

```{r example}
library(primer)

# random finite rates of increase
lambdas <- runif(10, .5, 1.5)

# stochastic dynamics
out <- PopSim(Rs=lambdas, years=50, N0=50)
matplot(0:50, out, type='l')

# distribution of final population sizes
summary(out[51,])
```


